### ISSUE TITLE
The problem about blob process

### ISSUE THREAD

**Issue by LusTerCsI** [ngthanhtin/Muiltiple-Object-Tracking#1]
So I find your code today and have a look at it, I have a question at line 152 in Source.cpp:
`for (int k = 0; k < b.size(); k++){ ... }`
The blob vector `b` don't have any elements in it, can this `for` loop be done?

I'm learning Computer Science for now so maybe I misunderstand your code, feel free to correct me if I'm wrong.

**Comment by ngthanhtin** [comment]
b is none when the image does not find any contours in it. This is a simple version of static object tracking (means that the camera is static), and I use background subtraction method to detect objects, Kalman filter plus Hungarian algorithm to track moving objects. If the camera is not static, this approach is not useful, so be careful when you follow this method.

**Comment by LusTerCsI** [comment]
Thanks for the quickly reply, I understand your code more now :smile: 
But I still have a question about the blob section: 
the `vector<Blob> b` define at line 65, but I don't see any `push_back` into the b vector,
doesn't that mean the `vector<Blob> b` will be maintain zero element?

**Comment by ngthanhtin** [comment]
oh, I have just updated this project. You can see in line 146, this is the process I push blob in to vector b

**Comment by LusTerCsI** [comment]
Ohh the new comments makes me more clearly to understand this, thanks a lot!
This is surely a good project ofr me to learn, keep going!

**Comment by LusTerCsI** [comment]
So I'm now want to write a similar project like yours, and I'm not sure which program to start with.
I only know Visual Studio, may I ask you what program do you use?

**Comment by LusTerCsI** [comment]
OK, I'll check it out. Thank you for your reply!
