### ISSUE TITLE
The problem about 1920*1080 avi file

### ISSUE THREAD

**Issue by dongdongtong** [ngthanhtin/Muiltiple-Object-Tracking#2]
When i use the 1920*1080 file of avi as the input to this program, i find this line of source.cpp file as below that shows a library runtime exception

`vector<vector<PixelHistogram>> arr(tmpFrame.rows, vector<PixelHistogram>(tmpFrame.cols)); // pixel histogram of each frame`

But when i use the avi file that <= 1920*1080, such as the avi file in the primitive project, there's no such problem.

... ... the problem is beyond my ability since i am a perfectly fresh guy to opencv, and i would be really grateful if you could teach me how to solve this problem..........

**Comment by dongdongtong** [comment]
and the runtime exception is 
The most probably exception: Microsoft C++ Exception: std::bad_alloc，Located in the 0x002BD5CC 
The most probably exception: Microsoft C++ Exception: [rethrow]，Located in the 0x00000000
The most probably exception: Microsoft C++ Exception: [rethrow]，Located in the 0x00000000

**Comment by dongdongtong** [comment]
Thanks God!  When i modify the running platform from win32 to 64, the hard nut has been cracked!

**Comment by ngthanhtin** [comment]
Hope it will be useful for you. Gook luck !!!
