### ISSUE TITLE
Could you tell me what is the differences between this project and SORT?

### ISSUE THREAD

**Issue by 123lifei** [ngthanhtin/Muiltiple-Object-Tracking#4]
I find that the assignment cost matrix is computed between each detection and all predicted bounding boxes from the existing targets. But this project the assignment cost matrix is
then computed between each detection and detection or tracking bbox of last frames？

**Comment by ngthanhtin** [comment]
The Deep SORT uses a pretrained feature (trained on MARS  dataset, i don't remember, you should check the sort paper) to detect people. In this project, I detect people as moving objects by using background subtraction method.
About the Data Association, I used the same method in SORT paper, this is Hungary Algorithm (in fact, I do not know about SORT paper when doing this one, I have done this 2 years ago).

**Comment by 123lifei** [comment]
Thank you very much for your reply.I find the assignment distances matrix is computed after kalman-tracker is updated in your project But in the SORT paper  the assignment distances matrix is computed after kalman prodictint. it means in your project the process is prodicting ，then update and Associated by Hungary Algorithm ，But in sort paper the process is predicting ，then  Associated by Hungary Algorithm and update。Is that right？Thank you

**Comment by ngthanhtin** [comment]
The idea is the same, I took a look at SORT paper as well as the code provided here: https://github.com/Qidian213/deep_sort_yolov3 and I found that I and they both calculated the assignment distances matrix in the Update process
